import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bar, Doughnut } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, ArcElement, Tooltip, Legend } from 'chart.js';
import './style.css';

ChartJS.register(CategoryScale, LinearScale, BarElement, ArcElement, Tooltip, Legend);
const API = import.meta.env.PROD ? '' : (import.meta.env.VITE_API_URL || '');
const categories = { income: ['Salary', 'Freelancing', 'Investments', 'Other income'], expense: ['Food', 'Shopping', 'Travel', 'Rent', 'Bills', 'Entertainment', 'Other expense'] };
const today = () => new Date().toLocaleDateString('en-CA');
const emptyForm = () => ({ title: '', amount: '', category: 'Food', date: today(), type: 'expense' });
const format = (amount, currency = 'INR') => new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 2 }).format(amount || 0);
async function request(path, options = {}, token) {
  const response = await fetch(API + '/api' + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  if (response.status === 204) return null;
  let data; try { data = await response.json(); } catch { throw new Error('The server is unavailable. Please try again.'); }
  if (!response.ok) throw new Error(data.error || 'Request failed.');
  return data;
}

function Auth({ onAuth }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ name: '', email: '', password: '' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setError(''); setBusy(true); try { onAuth(await request('/auth/' + mode, { method: 'POST', body: JSON.stringify(form) })); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="auth-shell"><div className="auth-brand"><div className="brand-mark">◈</div><h1>Know where your money goes.</h1><p>A clear view of your income, spending and savings—all in one place.</p><div className="auth-art"><span>Monthly overview</span><strong>Make every number count.</strong><div className="art-bars"><i/><i/><i/><i/><i/><i/><i/></div></div></div><div className="auth-panel"><div className="mobile-brand">◈ <b>Ledger</b></div><div className="auth-card"><div className="eyebrow">PERSONAL FINANCE, SIMPLIFIED</div><h2>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><p>{mode === 'login' ? 'Sign in to see your finances.' : 'Start tracking what matters to you.'}</p><form onSubmit={submit}>{mode === 'register' && <label>Your name<input required maxLength="80" autoComplete="name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name"/></label>}<label>Email address<input required type="email" autoComplete="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com"/></label><label>Password<input required type="password" minLength="8" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters"/></label>{error && <div className="alert" role="alert">{error}</div>}<button className="primary full" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><div className="auth-switch">{mode === 'login' ? 'New to Ledger?' : 'Already have an account?'} <button onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></div></div></div></div>;
}

function App() {
  const [session, setSession] = useState(() => { try { return JSON.parse(localStorage.getItem('ledger-session')); } catch { return null; } });
  const [view, setView] = useState('overview'); const [report, setReport] = useState(null); const [list, setList] = useState({ items: [], total: 0, page: 1, pages: 1 });
  const [filters, setFilters] = useState({ search: '', type: '', category: '', month: '', minAmount: '', maxAmount: '', date: '' });
  const [month, setMonth] = useState(today().slice(0,7)); const [page, setPage] = useState(1); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const [editor, setEditor] = useState(null); const [profileOpen, setProfileOpen] = useState(false); const [profile, setProfile] = useState({ name: '', currency: 'INR' }); const [notice, setNotice] = useState(''); const [version, setVersion] = useState(0);
  const token = session?.token, currency = session?.user?.currency || 'INR';
  function onAuth(next) { localStorage.setItem('ledger-session', JSON.stringify(next)); setSession(next); }
  function logout() { localStorage.removeItem('ledger-session'); setSession(null); setReport(null); setList({ items: [], total: 0, page: 1, pages: 1 }); }
  useEffect(() => { if (!token) return; request('/me', {}, token).then(({ user }) => { setSession(s => { if (!s) return s; const next = { ...s, user }; localStorage.setItem('ledger-session', JSON.stringify(next)); return next; }); }).catch(err => { if (err.message === 'Please sign in again.') logout(); }); }, [token]);
  useEffect(() => { if (!token) return; let active = true; setLoading(true); setError(''); const params = new URLSearchParams({ page: String(page), limit: '10' }); for (const [key, val] of Object.entries(filters)) if (val) params.set(key, val); Promise.all([request('/reports?month=' + month, {}, token), request('/transactions?' + params, {}, token)]).then(([r, l]) => { if (active) { setReport(r); setList(l); } }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [token, month, page, filters, version]);
  function changeFilter(key, value) { setPage(1); setFilters(f => ({ ...f, [key]: value })); }
  async function saveTransaction(e) { e.preventDefault(); setError(''); const { id, ...data } = editor; try { await request(id ? '/transactions/' + id : '/transactions', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(data) }, token); setEditor(null); setVersion(v => v + 1); setNotice(id ? 'Transaction updated.' : 'Transaction added.'); } catch (err) { setError(err.message); } }
  async function remove(item) { if (!window.confirm(`Delete “${item.title}”?`)) return; try { await request('/transactions/' + item.id, { method: 'DELETE' }, token); setVersion(v => v + 1); setNotice('Transaction deleted.'); } catch (err) { setError(err.message); } }
  async function saveProfile(e) { e.preventDefault(); try { const result = await request('/me', { method: 'PATCH', body: JSON.stringify(profile) }, token); onAuth({ ...session, user: result.user }); setProfileOpen(false); setNotice('Profile updated.'); } catch (err) { setError(err.message); } }
  const chartMonths = useMemo(() => Object.keys(report?.monthly || {}).sort().slice(-6), [report]);
  function exportCsv() { const params = new URLSearchParams({ limit: '100', page: '1' }); for (const [key, val] of Object.entries(filters)) if (val) params.set(key, val); (async () => { try { let rows = [], current = 1, pages = 1; do { params.set('page', current); const result = await request('/transactions?' + params, {}, token); rows.push(...result.items); pages = result.pages; current++; } while (current <= pages); const cell = value => `"${String(value ?? '').replaceAll('"', '""')}"`; const csv = ['Date,Title,Category,Type,Amount', ...rows.map(x => [x.date, x.title, x.category, x.type, x.amount].map(cell).join(','))].join('\r\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'ledger-transactions.csv'; a.click(); URL.revokeObjectURL(url); } catch (err) { setError(err.message); } })(); }
  if (!session) return <Auth onAuth={onAuth}/>;
  return <div className="app-shell"><aside className="sidebar"><div className="logo"><span className="brand-mark">◈</span> Ledger</div><div className="side-label">WORKSPACE</div><nav aria-label="Main navigation">{[['overview','▦','Overview'],['transactions','⇄','Transactions'],['reports','◫','Reports']].map(([key, icon, label]) => <button key={key} className={view === key ? 'active' : ''} onClick={() => setView(key)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">{session.user.name.charAt(0).toUpperCase()}</div><div><strong>{session.user.name}</strong><small>{session.user.email}</small></div><button className="menu-dots" aria-label="Edit profile" onClick={() => { setProfile({ name: session.user.name, currency }); setProfileOpen(true); }}>⋯</button></div></aside><main className="main"><header className="topbar"><div className="mobile-brand">◈ <b>Ledger</b></div><span className="top-note">Your personal finance workspace</span><div className="top-actions"><span className="user-pill">{session.user.name}</span><button className="text-button" onClick={logout}>Log out</button></div></header><div className="content">{notice && <div className="notice" role="status">{notice}<button aria-label="Dismiss" onClick={() => setNotice('')}>×</button></div>}{error && <div className="alert" role="alert">{error}<button aria-label="Dismiss" onClick={() => setError('')}>×</button></div>}<div className="page-heading"><div><div className="eyebrow">YOUR MONEY AT A GLANCE</div><h1>{view === 'overview' ? 'Overview' : view === 'transactions' ? 'Transactions' : 'Reports'}</h1><p>{view === 'overview' ? 'See the full picture, one transaction at a time.' : view === 'transactions' ? 'Find, manage and export your activity.' : 'Understand how your money moved this month.'}</p></div><button className="primary" onClick={() => { setEditor(emptyForm()); setError(''); }}>＋ Add transaction</button></div>
  {loading && !report ? <div className="panel empty">Loading your finances…</div> : <>
  {view === 'overview' && <><section className="metrics"><Metric label="Total income" value={format(report?.totalIncome, currency)} icon="↗" tone="mint"/><Metric label="Total expenses" value={format(report?.totalExpenses, currency)} icon="↘" tone="peach"/><Metric label="Current balance" value={format(report?.balance, currency)} icon="◎" tone="blue"/><Metric label="Monthly spending" value={format(report?.expenses, currency)} icon="◴" tone="purple"/></section><div className="section-head"><div><h2>Money in, money out</h2><p>Your income and expenses over the last six active months</p></div></div><div className="chart-grid"><div className="panel chart-panel"><div className="panel-title"><h3>Cash flow</h3><span>Last 6 active months</span></div>{chartMonths.length ? <div className="chart-box"><Bar data={{ labels: chartMonths.map(x => new Date(x + '-01T00:00:00').toLocaleDateString('en', { month: 'short', year: '2-digit' })), datasets: [{ label: 'Income', data: chartMonths.map(x => report.monthly[x].income), backgroundColor: '#35b78b', borderRadius: 5 }, { label: 'Expenses', data: chartMonths.map(x => report.monthly[x].expenses), backgroundColor: '#91a9f8', borderRadius: 5 }] }} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom' } }, scales: { x: { grid: { display: false } }, y: { beginAtZero: true } } }}/></div> : <Empty/>}</div><div className="panel chart-panel"><div className="panel-title"><h3>Spending by category</h3><input aria-label="Report month" type="month" value={month} onChange={e => setMonth(e.target.value)}/></div>{Object.keys(report?.categories || {}).length ? <div className="chart-box doughnut"><Doughnut data={{ labels: Object.keys(report.categories), datasets: [{ data: Object.values(report.categories), backgroundColor: ['#3859d8','#69ba9b','#f7a75e','#9a88d6','#e77985','#75b9d1','#bac2d2'], borderWidth: 0 }] }} options={{ responsive: true, maintainAspectRatio: false, cutout: '67%', plugins: { legend: { position: 'bottom', labels: { boxWidth: 11, padding: 15 } } } }}/></div> : <Empty text="No expenses for this month yet."/>}</div></div><div className="section-head"><div><h2>Recent transactions</h2><p>Your latest activity</p></div><button className="text-button" onClick={() => setView('transactions')}>View all →</button></div><TransactionTable items={list.items.slice(0,5)} currency={currency} onEdit={setEditor} onDelete={remove}/></>}
  {view === 'transactions' && <><div className="panel filters"><label>Search<input placeholder="Search titles" value={filters.search} onChange={e => changeFilter('search', e.target.value)}/></label><label>Type<select value={filters.type} onChange={e => changeFilter('type', e.target.value)}><option value="">All types</option><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Category<select value={filters.category} onChange={e => changeFilter('category', e.target.value)}><option value="">All categories</option>{[...categories.income, ...categories.expense].map(c => <option key={c}>{c}</option>)}</select></label><label>Month<input type="month" value={filters.month} onChange={e => changeFilter('month', e.target.value)}/></label><label>Exact date<input type="date" value={filters.date} onChange={e => changeFilter('date', e.target.value)}/></label><label>Min amount<input type="number" min="0" placeholder="0" value={filters.minAmount} onChange={e => changeFilter('minAmount', e.target.value)}/></label><label>Max amount<input type="number" min="0" placeholder="Any" value={filters.maxAmount} onChange={e => changeFilter('maxAmount', e.target.value)}/></label><button className="outline" onClick={() => { setFilters({ search: '', type: '', category: '', month: '', minAmount: '', maxAmount: '', date: '' }); setPage(1); }}>Clear filters</button></div><div className="section-head"><div><h2>Transaction history</h2><p>{list.total} {list.total === 1 ? 'transaction' : 'transactions'} found</p></div><button className="outline" onClick={exportCsv}>↓ Export CSV</button></div><TransactionTable items={list.items} currency={currency} onEdit={setEditor} onDelete={remove}/><div className="pagination"><button disabled={page <= 1} onClick={() => setPage(p => p - 1)}>← Previous</button><span>Page {list.page} of {list.pages}</span><button disabled={page >= list.pages} onClick={() => setPage(p => p + 1)}>Next →</button></div></>}
  {view === 'reports' && <><div className="report-heading"><label>Report month<input type="month" value={month} onChange={e => setMonth(e.target.value)}/></label><button className="outline" onClick={() => window.print()}>Print / Save PDF</button></div><section className="metrics"><Metric label="Monthly income" value={format(report?.income,currency)} icon="↗" tone="mint"/><Metric label="Monthly expenses" value={format(report?.expenses,currency)} icon="↘" tone="peach"/><Metric label="Monthly savings" value={format(report?.savings,currency)} icon="◎" tone="blue"/><Metric label="Spending / income" value={report?.spendingPercentage == null ? '—' : report.spendingPercentage.toFixed(1) + '%'} icon="◴" tone="purple"/></section><div className="chart-grid"><div className="panel chart-panel"><div className="panel-title"><h3>Income vs expenses</h3></div>{chartMonths.length ? <div className="chart-box"><Bar data={{ labels: chartMonths, datasets: [{ label: 'Income', data: chartMonths.map(x => report.monthly[x].income), backgroundColor: '#35b78b', borderRadius: 5 }, { label: 'Expenses', data: chartMonths.map(x => report.monthly[x].expenses), backgroundColor: '#91a9f8', borderRadius: 5 }] }} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom' } } }}/></div> : <Empty/>}</div><div className="panel chart-panel"><div className="panel-title"><h3>Expense breakdown</h3></div>{Object.keys(report?.categories || {}).length ? <div className="category-list">{Object.entries(report.categories).sort((a,b) => b[1]-a[1]).map(([key, value], i) => <div className="category-row" key={key}><span className="category-dot" style={{ background: ['#3859d8','#69ba9b','#f7a75e','#9a88d6','#e77985','#75b9d1','#bac2d2'][i % 7] }}/><span>{key}</span><strong>{format(value,currency)}</strong><div className="progress"><i style={{ width: `${value / report.expenses * 100}%` }}/></div></div>)}</div> : <Empty text="No expenses for this month yet."/>}</div></div></>}
  </>}</div></main><nav className="bottom-nav" aria-label="Mobile navigation">{[['overview','▦','Overview'],['transactions','⇄','Activity'],['reports','◫','Reports']].map(([key, icon, label]) => <button key={key} className={view === key ? 'active' : ''} onClick={() => setView(key)}><span>{icon}</span>{label}</button>)}</nav>
  {editor && <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) setEditor(null); }}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="transaction-heading"><div className="modal-top"><div><div className="eyebrow">TRANSACTION</div><h2 id="transaction-heading">{editor.id ? 'Edit transaction' : 'Add transaction'}</h2></div><button aria-label="Close" className="close" onClick={() => setEditor(null)}>×</button></div><form onSubmit={saveTransaction}><div className="type-toggle">{['expense','income'].map(type => <button type="button" key={type} className={editor.type === type ? 'selected' : ''} onClick={() => setEditor({ ...editor, type, category: categories[type][0] })}>{type === 'income' ? '↗ Income' : '↘ Expense'}</button>)}</div><label>Title<input required maxLength="100" value={editor.title} onChange={e => setEditor({ ...editor, title: e.target.value })} placeholder="e.g. Groceries"/></label><label>Amount<input required type="number" min="0.01" max="1000000000000" step="0.01" value={editor.amount} onChange={e => setEditor({ ...editor, amount: e.target.value })} placeholder="0.00"/></label><div className="form-row"><label>Category<select value={editor.category} onChange={e => setEditor({ ...editor, category: e.target.value })}>{categories[editor.type].map(c => <option key={c}>{c}</option>)}</select></label><label>Date<input required type="date" value={editor.date} onChange={e => setEditor({ ...editor, date: e.target.value })}/></label></div><div className="modal-actions"><button type="button" className="outline" onClick={() => setEditor(null)}>Cancel</button><button className="primary">Save transaction</button></div></form></div></div>}
  {profileOpen && <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) setProfileOpen(false); }}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="profile-heading"><div className="modal-top"><h2 id="profile-heading">Your profile</h2><button className="close" aria-label="Close" onClick={() => setProfileOpen(false)}>×</button></div><form onSubmit={saveProfile}><label>Name<input required value={profile.name} onChange={e => setProfile({ ...profile, name: e.target.value })}/></label><label>Display currency<select value={profile.currency} onChange={e => setProfile({ ...profile, currency: e.target.value })}><option value="INR">INR — Indian rupee</option><option value="USD">USD — US dollar</option><option value="EUR">EUR — Euro</option><option value="GBP">GBP — British pound</option></select></label><p className="hint">Changing currency changes the display symbol; it does not convert amounts.</p><button className="primary full">Save profile</button></form></div></div>}
  </div>;
}
function Metric({ label, value, icon, tone }) { return <div className="metric"><div className={'metric-icon ' + tone}>{icon}</div><span>{label}</span><strong>{value}</strong></div>; }
function Empty({ text = 'No data yet. Add a transaction to get started.' }) { return <div className="empty"><span>◌</span><p>{text}</p></div>; }
function TransactionTable({ items, currency, onEdit, onDelete }) { return <div className="panel table-wrap">{!items.length ? <Empty text="No transactions found. Add one or adjust your filters."/> : <table><thead><tr><th>Date</th><th>Transaction</th><th>Category</th><th>Type</th><th className="align-right">Amount</th><th className="align-right">Actions</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{new Date(item.date + 'T00:00:00').toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</td><td className="title-cell"><span className={'transaction-icon ' + item.type}>{item.type === 'income' ? '↗' : '↘'}</span>{item.title}</td><td>{item.category}</td><td><span className={'type-badge ' + item.type}>{item.type}</span></td><td className={'align-right amount ' + item.type}>{item.type === 'income' ? '+' : '−'}{format(item.amount,currency)}</td><td className="align-right actions"><button aria-label={`Edit ${item.title}`} onClick={() => onEdit({ ...item })}>Edit</button><button aria-label={`Delete ${item.title}`} onClick={() => onDelete(item)}>Delete</button></td></tr>)}</tbody></table>}</div>; }

createRoot(document.getElementById('root')).render(<App/>);
